// Generated by gencpp from file test_pkg/Num.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_NUM_H
#define TEST_PKG_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num(0)
    , bigger_num(0)
    , NumNumNum(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num(0)
    , bigger_num(0)
    , NumNumNum(0)  {
  (void)_alloc;
    }



   typedef int8_t _num_type;
  _num_type num;

   typedef int16_t _bigger_num_type;
  _bigger_num_type bigger_num;

   typedef int8_t _NumNumNum_type;
  _NumNumNum_type NumNumNum;





  typedef boost::shared_ptr< ::test_pkg::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::test_pkg::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::test_pkg::Num > NumPtr;
typedef boost::shared_ptr< ::test_pkg::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::Num_<ContainerAllocator1> & lhs, const ::test_pkg::Num_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.bigger_num == rhs.bigger_num &&
    lhs.NumNumNum == rhs.NumNumNum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::Num_<ContainerAllocator1> & lhs, const ::test_pkg::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6984b6b29b1a95096bc45ddb5f33ba67";
  }

  static const char* value(const ::test_pkg::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6984b6b29b1a9509ULL;
  static const uint64_t static_value2 = 0x6bc45ddb5f33ba67ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/Num";
  }

  static const char* value(const ::test_pkg::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num\n"
"int16 bigger_num\n"
"int8 NumNumNum\n"
;
  }

  static const char* value(const ::test_pkg::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.bigger_num);
      stream.next(m.NumNumNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::Num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num);
    s << indent << "bigger_num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.bigger_num);
    s << indent << "NumNumNum: ";
    Printer<int8_t>::stream(s, indent + "  ", v.NumNumNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_NUM_H
