
amcl:
  ros__parameters:
    min_particles: 500
    max_particles: 3000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.8
    alpha4: 0.1
    alpha5: 0.1
    laser_max_range: 10.0
    laser_min_range: 0.05
    z_hit: 0.95
    z_short: 0.1
    z_max: 0.05
    z_rand: 0.05
    sigma_hit: 0.2
    lambda_short: 0.1
    initial_pose_x: -2.0
    initial_pose_y: -0.5
    initial_pose_a: 0.0
    initial_pose_covariance: [0.5, 0, 0, 0, 0.5, 0, 0, 0, 0.1]
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    odom_model_type: "diff"
    use_map_topic: false
    scan_topic: "scan"

